export const FETCH_LOGIN_DATA = "FETCH_LOGIN_DATA";
export const FETCH_WORKSPACES = "FETCH_WORKSPACES";
export const NEW_WORKSPACE = "NEW_WORKSPACE";
export const CREATE_FORM_DATA = "CREATE_FORM_DATA";
export const WORKSPACE_FORMS = "WORKSPACE_FORMS";
export const FORM_RESPONSE_STATUS = "FORM_RESPONSE_STATUS";
